version: '3'

services:
<<<<<<< HEAD
  core:
=======
  mvp-backend:
>>>>>>> 843687a96f49fa12d814510d54075b6132726729
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: core
    ports:
      - '8080:8080'
    depends_on:
<<<<<<< HEAD
      db:
=======
      mvp-db:
>>>>>>> 843687a96f49fa12d814510d54075b6132726729
        condition: service_healthy
    networks:
      - frontend2backend

<<<<<<< HEAD
  db:
    image: postgres:15.1
    hostname: db
=======
  mvp-db:
    image: postgres:15.1
    hostname: mvp-db
>>>>>>> 843687a96f49fa12d814510d54075b6132726729
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graphs
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d graphs" ]
      interval: 10s
      timeout: 5s
      retries: 150
      start_period: 20s
    networks:
      - frontend2backend

networks:
  frontend2backend:
    external: true